name: Environment Suite

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - jszwedko/build-dev-image-arm64

env:
  VERBOSE: true
  CI: true

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        docker:
          - { runner: ubuntu-20.04, platform: linux/amd64 }
          - { runner: ubuntu-24.04-4core-arm, platform: linux/arm64 }
    runs-on: ${{ matrix.docker.runner }}
    timeout-minutes: 30
    steps:
      - name: (PR review) Set latest commit status as pending
        if: ${{ github.event_name == 'pull_request_review' }}
        uses: myrotvorets/set-commit-status-action@v2.0.1
        with:
          sha: ${{ github.event.review.commit_id }}
          token: ${{ secrets.GITHUB_TOKEN }}
          context: Environment Suite
          status: pending

      - name: (PR review) Checkout PR branch
        if: ${{ github.event_name == 'pull_request_review' }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.review.commit_id }}

      - name: Prepare environment
        run: |
          platform=${{ matrix.docker.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: timberio/vector-dev
          flavor: |
            latest=true
          tags: type=sha, format=long
          labels: |
            org.opencontainers.image.description=Image for Vector's Docker development environment
            org.opencontainers.image.source=https://github.com/vectordotdev/vector/tree/jszwedko/build-dev-image-arm64/scripts/environment/Dockerfile
            org.opencontainers.image.title=Vector development environment
            org.opencontainers.image.url=https://github.com/vectordotdev/vector

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
      - name: Login to DockerHub
        uses: docker/login-action@v3
        if: github.ref == 'refs/heads/jszwedko/build-dev-image-arm64'
        with:
          username: ${{ secrets.CI_DOCKER_USERNAME }}
          password: ${{ secrets.CI_DOCKER_PASSWORD }}

      - name: Checkout branch
        if: ${{ github.event_name != 'pull_request_review' }}
        uses: actions/checkout@v4

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6.9.0
        with:
          context: .
          file: ./scripts/environment/Dockerfile
          push: ${{ github.ref == 'refs/heads/jszwedko/build-dev-image-arm64' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ matrix.docker.platform }}
          outputs: type=image,name=timberio/vector-dev,push-by-digest=true,name-canonical=true,push=true

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          touch "/tmp/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: /tmp/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: /tmp/digests
          pattern: digests-*
          merge-multiple: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: timberio/vector-dev
          flavor: |
            latest=true
          tags: type=sha, format=long
          labels: |
            org.opencontainers.image.description=Image for Vector's Docker development environment
            org.opencontainers.image.source=https://github.com/vectordotdev/vector/tree/jszwedko/build-dev-image-arm64/scripts/environment/Dockerfile
            org.opencontainers.image.title=Vector development environment
            org.opencontainers.image.url=https://github.com/vectordotdev/vector

      - name: Login to DockerHub
        uses: docker/login-action@v3
        if: github.ref == 'refs/heads/jszwedko/build-dev-image-arm64'
        with:
          username: ${{ secrets.CI_DOCKER_USERNAME }}
          password: ${{ secrets.CI_DOCKER_PASSWORD }}

      - name: Create manifest list and push
        working-directory: /tmp/digests
        if: github.ref == 'refs/heads/jszwedko/build-dev-image-arm64'
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
            $(printf 'timberio/vector-dev@sha256:%s ' *)

      - name: Inspect image
        run: |
          docker buildx imagetools inspect timberio/vector-dev:${{ steps.meta.outputs.version }}

      - name: (PR review) Set latest commit status as ${{ job.status }}
        uses: myrotvorets/set-commit-status-action@v2.0.1
        if: always() && github.event_name == 'pull_request_review'
        with:
          sha: ${{ github.event.review.commit_id }}
          token: ${{ secrets.GITHUB_TOKEN }}
          context: Environment Suite
          status: ${{ job.status }}
